name: 'Get the latest repo tag'
description: 'Get the current tag and return the next tag'
inputs:
  currentTag:  # id of input
    description: 'Latest git tags'
    required: true
outputs:
  nextTag: # id of output
    description: 'New Tag'
runs:
  using: 'node16'
  main: '.github/workflows/scripts/getTag.ts'