name: 'Get the latest repo tag'
description: 'Get the current tag and return the next tag'
inputs:
  gitTags:  # id of input
    description: 'Latest git tags'
    required: true
    default: 'release_1.00.1_rc1'
outputs:
  newTag: # id of output
    description: 'New Tag'
runs:
  using: 'node20'
  main: '.github/workflows/scripts/getTag.ts'