name: Cherry-pick PR for Release Branch
on:
  push:
    branches: ['release/**']
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # - name: Check merge conflicts
      #   run : |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git fetch origin 
      #     git merge --no-commit origin/main
      #     # if [ $? -ne 0 ]; then
      #     #     echo there are conflicts
      #     # fi
    
      # - uses: nokamoto/merge-conflict-action@v0.0.4
      #   with:
      #     owner: nokamoto
      #     repo: merge-conflict-action
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - uses: prince-chrismc/label-merge-conflicts-action@v3
        with:
          conflict_label_name: "has conflict"
          github_token: ${{ github.token }}

          # --- Optional Inputs ---
          # To make sure the merge commit exactly matches the branch
          detect_merge_changes: false # or true to handle as conflicts
          # By default a comment will be left, adding `conflict_comment: ''` will disable comments
          # The optional `${author}` will be replaced with the username of the pull request
          conflict_comment: |
            :wave: Hi, @${user.name},
            I detected conflicts against the base branch :speak_no_evil:
            You'll want to sync :arrows_counterclockwise: your branch with upstream!

      
      # - name: Run the Action
      #   if: startsWith(github.ref, 'refs/heads/release')
      #   uses: devops-infra/action-pull-request@v0.5.5
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     title: ${{ github.event.commits[0].message }}
      #     assignee: ${{ github.actor }}
      #     label: automatic,release
      #     new_string: ${{ github.event.commits[0].message }}
      #     get_diff: true
      #     target_branch : 'main'
      #     source_branch : ${{ github.head_ref || github.ref_name }} 

      # - name: Merge Conflict finder
      #   uses: olivernybroe/action-conflict-finder@v2.0
     