# name: Cherry-pick PR

# # on:
# #   pull_request_review:
# #     types: [submitted]
# on:
#   workflow_dispatch:
# jobs:
#   build:
#     if: github.event.review.state == 'approved'
#     runs-on: ubuntu-latest

#     steps:
#     - name: create pull request
#       run: gh pr create -B main -H branch_to_merge --title 'Merge branch_to_merge into main' --body 'Created by Github action'
#       env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: Run the Action on each commit
on:
  push:
    branches-ignore: [main]
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run the Action
        # if: startsWith(github.ref, 'refs/heads/relase')
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          assignee: ${{ github.actor }}
          label: automatic,relase
          # template: .github/PULL_REQUEST_TEMPLATE/FEATURE.md
          old_string: "**Write you description here**"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true