name: Cherry-pick PR for Release Branch
on:
  push:
    branches: ['release/**']
jobs:
  Cherry-pick_PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Check merge conflicts
        run : |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --no-commit --no-ff origin main
          echo ::set-output name=exit_code::$?
          echo "Exited with $?"

      # - name : Notify to the user if conflicts found
      #   if: ${{ failure() }}
      #   uses: prince-chrismc/label-merge-conflicts-action@v3
      #   with:
      #     conflict_label_name: "has conflict"
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     detect_merge_changes: false 
      #     conflict_comment: |
      #       :wave: Hi, ${{github.actor}},
      #       I detected conflicts against the base branch.
      #       Please resolve the conflict.
      - name: Send mail
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          connection_url: ${{secrets.MAIL_CONNECTION}}
          # https://github.com/gauravshrivas47405/gitactions/ 
          # ${{secrets.MAIL_CONNECTION}}
          # Required mail server address if not connection_url:
          server_address: smtp.github.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          # username: ${{secrets.MAIL_USERNAME}}
          # # Optional (recommended) mail server password:
          # password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: gaurav.shrivas@zensar.com
          # Required sender full name (address can be skipped):
          from: gaurav.shrivas@zensar.com # <user@example.com>
          priority: High

      - name: Create Cherry-pick PR
        if: ${{ startsWith(github.ref, 'refs/heads/release') && success() }}
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          assignee: ${{ github.actor }}
          label: hot-fix
          new_string: ${{ github.event.commits[0].message }}
          target_branch : 'main'
          source_branch : ${{ github.head_ref || github.ref_name }} 