name: Cherry-pick PR for Release Branch
on:
  push:
    branches: ['release/**']
jobs:
  Cherry-pick_PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Check merge conflicts
        run : |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --no-commit --no-ff origin main
          # echo "Conflict found and exit" && exit 1
          echo ::set-output name=exit_code::$?
          echo "Exited with $?"


      # - name : Notify to the user if conflicts found
      #   if: ${{ failure() }}
      #   uses: prince-chrismc/label-merge-conflicts-action@v3
      #   with:
      #     conflict_label_name: "has conflict"
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     detect_merge_changes: false 
      #     conflict_comment: |
      #       :wave: Hi, ${{github.actor}},
      #       I detected conflicts against the base branch.
      #       Please resolve the conflict.

      - name : Notify to the user if conflicts found
        if: ${{ failure() }}
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow Failed
          body: Conflict found
          to: gaurav.shrivas@zensar.con
          from: notifications@github.com

      - name: Create Cherry-pick PR
        if: ${{ startsWith(github.ref, 'refs/heads/release') && success() }}
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          assignee: ${{ github.actor }}
          label: hot-fix
          new_string: ${{ github.event.commits[0].message }}
          target_branch : 'main'
          source_branch : ${{ github.head_ref || github.ref_name }} 