name: Cherry-pick PR for Release Branch
on:
  push:
    branches: ['release/**']
jobs:
  Cherry-pick_PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
     
      - name: Check merge conflicts
        run : |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --no-commit --no-ff origin main
         

      # - name : Notify to the developer if conflicts found
      #   uses: neonidian/teams-notify-build-status@v3
      #   if: ${{ !success() }} 
      #   with:
      #     webhookUrl: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
      #     message: >-
      #       Hi ${{github.actor}},

      #       Failed to create PR, Your recent commit ${{ github.event.commits[0].message }} has merge conflicts.
            
      #       Please raise the PR manually.
      #     status: Failure
          
      - name : Notify to the developer if PR title validation fail
        if: ${{ !success() && !startsWith('FIX(',github.event.commits[0].message) && !contains(fromJson('["-",":"]'), github.event.commits[0].message)}} 
        run: |
          echo "Test Pass with valid PR"
          echo  ${{startsWith('FIX(',github.event.commits[0].message)}}
        #   echo  ${{contains(fromJson('["FIX"]'), github.event.commits[0].message)}}
        # uses: neonidian/teams-notify-build-status@v3
        # with:
        #   webhookUrl: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
        #   message: >-
        #     Hi ${{github.actor}},
            
        #     We require pull request titles to follow the PR Title Conventions and it looks like your proposed title needs to be adjusted.
        #   status: Failure
          
      - name: Create Cherry-pick PR
        if: ${{ startsWith(github.ref, 'refs/heads/release') && success() }}
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          assignee: ${{ github.actor }}
          label: hot-fix
          new_string: ${{ github.event.commits[0].message }}
          target_branch : 'main'
          source_branch : ${{ github.head_ref || github.ref_name }} 