name: Cherry-pick PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:

      - name: Create Release Branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "::Checking if workfolw executed or not"