name: Cherry-pick PR for Release Branch
on:
  push:
    branches: ['release/**']
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run the Action
        if: startsWith(github.ref, 'refs/heads/release')
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          assignee: ${{ github.actor }}
          label: automatic,release
          # template: .github/PULL_REQUEST_TEMPLATE/FEATURE.md
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true
          target_branch : 'main'
          source_branch : ${{ github.head_ref || github.ref_name }} 