name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version no of release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Create Release Branch
        run: |
          git checkout -b release/${{inputs.release_version}}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          sed -ie 's/version .*/version ${{inputs.release_version}}/' app.json
          git add .
          git commit -m "Automated commit by GitHub Actions to update version name" -a
          git push --set-upstream origin release/${{inputs.release_version}}
          echo "::Release branch creadted successfully"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1

      - uses: winterjung/split@v2
        id: split
        with:
          msg: '/_rc'
      - name: Create tag
        uses: actions/github-script@v5

        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/release_${{inputs.release_version}}_rc${{steps.previoustag.outputs.tag}}',
              sha: context.sha
            })
      # - name: Create Release Tags
      #   uses: christophebedard/tag-version-commit@v1
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false
      #     version_tag_prefix: 'v'
