name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version no of release'
        type: number
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      # - uses: nowsprinting/check-version-format-action@v3
      #   id: version
      #   with:
      #     prefix: 'v${{inputs.release_version}}'

      # - name: Version tag only step
      #   run: |
      #     echo "Found valid version format in tag!"
      #     echo "Full version: ${{ steps.version.outputs.full }}"
      #     echo "Major version: ${{ steps.version.outputs.major }}"
      #     echo "Major with pre-release: ${{ steps.version.outputs.major_prerelease }}"
      #   if: steps.version.outputs.is_valid == 'true'

      # git tag -l 'release_*_rc*' | sort -V

      - name: Get the previous release Tag
        id : previous_release_tag
        run: |
          git tag -l 'release_*_rc*' | sort -V
      
      - name: Create Release Branch
        run: |
          git checkout -b release/${{inputs.release_version}}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          sed -ie 's/version .*/version ${{inputs.release_version}}/' app.json
          git add .
          git commit -m "Automated commit by GitHub Actions to update version name" -a
          git push --set-upstream origin release/${{inputs.release_version}}
          echo "::Release branch creadted successfully"
          echo "::Previous release tag ${{steps.previous_release_tag.outputs.tag}}"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1
          # prefix: 'release'
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag


      - name: Install dependencies
        run: npm i @actions/core @actions/github

      - name: Get Incremented Tag Value
        id: latestTag
        uses: ./
        with:
          currentTag: '${{steps.get-latest-tag.outputs.tag}}'
        
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/dev_${{inputs.release_version}}_rc${{steps.latestTag.outputs.nextTag}}',
              sha: context.sha
            })
          run : |
            git push origin --tags





            